#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#bd93f9'
TEXT='#bd93f9'
WRONG='#282a36'
VERIFYING='#bd93f9'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 3                     \
--clock                      \
--indicator                  \
--time-str="%H:%M"        \
--date-str="%A, %Y-%m-%d"       \
\
--screen 2                   \
--blur 3                     \
--clock                      \
--indicator                  \
--time-str="%H:%M"        \
--date-str="%A, %Y-%m-%d"       \
\
--screen 3                  \
--blur 3                     \
--clock                      \
--indicator                  \
--time-str="%H:%M"        \
--date-str="%A, %Y-%m-%d"       \